#ifndef FLUX_OPCODES_H
#define FLUX_OPCODES_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

// ISA v2 Specification
typedef enum {
    // System: 0x00-0x07
    FLUX_HALT=0x00,
    FLUX_NOP=0x01,
    FLUX_RET=0x02,
    FLUX_BRK=0x04,

    // Single register: 0x08-0x0F
    FLUX_INC=0x08,
    FLUX_DEC=0x09,
    FLUX_NOT=0x0A,
    FLUX_NEG=0x0B,
    FLUX_PUSH=0x0C,
    FLUX_POP=0x0D,

    // Immediate: 0x18-0x1F
    FLUX_MOVI=0x18,
    FLUX_ADDI=0x19,

    // Arithmetic: 0x20-0x2B
    FLUX_ADD=0x20,
    FLUX_SUB=0x21,
    FLUX_MUL=0x22,
    FLUX_DIV=0x23,
    FLUX_MOD=0x24,
    FLUX_AND=0x25,
    FLUX_OR=0x26,
    FLUX_XOR=0x27,
    FLUX_SHL=0x28,
    FLUX_SHR=0x29,

    // Compare: 0x2C-0x2F
    FLUX_CMP_EQ=0x2C,
    FLUX_CMP_LT=0x2D,
    FLUX_CMP_GT=0x2E,
    FLUX_CMP_NE=0x2F,

    // Float: 0x30-0x37
    FLUX_FADD=0x30,
    FLUX_FSUB=0x31,
    FLUX_FMUL=0x32,
    FLUX_FDIV=0x33,
    FLUX_FMIN=0x34,
    FLUX_FMAX=0x35,

    // Memory: 0x38-0x3B
    FLUX_LOAD=0x38,
    FLUX_STORE=0x39,
    FLUX_MOV=0x3A,
    FLUX_SWP=0x3B,

    // Branch: 0x3C-0x3F
    FLUX_JZ=0x3C,
    FLUX_JNZ=0x3D,
    FLUX_JLT=0x3E,
    FLUX_JGT=0x3F,

    // Jump: 0x43-0x46
    FLUX_JMP=0x43,
    FLUX_JAL=0x44,
    FLUX_CALL=0x45,
    FLUX_LOOP=0x46,

    // A2A: 0x50-0x53
    FLUX_TELL=0x50,
    FLUX_ASK=0x51,
    FLUX_DELEG=0x52,
    FLUX_BCAST=0x53,

    // Extended opcodes (implementation-specific): 0x60-0x84
    FLUX_DELEGATE=0x52,  // Alias for DELEG
    FLUX_DELEGATE_RESULT=0x63,
    FLUX_REPORT_STATUS=0x64,
    FLUX_REQUEST_OVERRIDE=0x65,
    FLUX_BROADCAST=0x66,
    FLUX_REDUCE=0x67,
    FLUX_DECLARE_INTENT=0x68,
    FLUX_ASSERT_GOAL=0x69,
    FLUX_VERIFY_OUTCOME=0x6A,
    FLUX_EXPLAIN_FAILURE=0x6B,
    FLUX_SET_PRIORITY=0x6C,
    FLUX_TRUST_CHECK=0x70,
    FLUX_TRUST_UPDATE=0x71,
    FLUX_TRUST_QUERY=0x72,
    FLUX_REVOKE_TRUST=0x73,
    FLUX_CAP_REQUIRE=0x74,
    FLUX_CAP_REQUEST=0x75,
    FLUX_CAP_GRANT=0x76,
    FLUX_CAP_REVOKE=0x77,
    FLUX_BARRIER=0x78,
    FLUX_SYNC_CLOCK=0x79,
    FLUX_FORMATION_UPDATE=0x7A,
    FLUX_EMERGENCY_STOP=0x7B,
    FLUX_YIELD=0x81,
    FLUX_RESOURCE_ACQUIRE=0x82,
    FLUX_RESOURCE_RELEASE=0x83,
    FLUX_DEBUG_BREAK=0x84,

    // Extended opcodes: 0x90-0x9F
    FLUX_DUP=0x90,
    FLUX_SWAP=0x91,
    FLUX_TEST=0x92,
    FLUX_SETCC=0x93,
    FLUX_ENTER=0x94,
    FLUX_LEAVE=0x95,
    FLUX_ALLOCA=0x96,
    FLUX_TAILCALL=0x97,
    FLUX_REGION_CREATE=0x98,
    FLUX_REGION_DESTROY=0x99,
    FLUX_REGION_TRANSFER=0x9A,
    FLUX_MEMCOPY=0x9B,
    FLUX_MEMSET=0x9C,
    FLUX_MEMCMP=0x9D,
    FLUX_CAST=0x9E,
    FLUX_BOX=0x9F,

    // Extended opcodes: 0xA0-0xAF
    FLUX_UNBOX=0xA0,
    FLUX_CHECK_TYPE=0xA1,
    FLUX_CHECK_BOUNDS=0xA2,
    FLUX_FNEG=0xA3,
    FLUX_FABS=0xA4,
    FLUX_FEQ=0xA5,
    FLUX_FLT=0xA6,
    FLUX_FLE=0xA7,
    FLUX_FGT=0xA8,
    FLUX_FGE=0xA9,
    FLUX_LOAD8=0xAA,
    FLUX_STORE8=0xAB,

    // Vector operations: 0xB0-0xBF
    FLUX_VLOAD=0xB0,
    FLUX_VSTORE=0xB1,
    FLUX_VADD=0xB2,
    FLUX_VSUB=0xB3,
    FLUX_VMUL=0xB4,
    FLUX_VDIV=0xB5,
    FLUX_VFMA=0xB6,

    // Legacy aliases for backward compatibility
    FLUX_IADD=FLUX_ADD,
    FLUX_ISUB=FLUX_SUB,
    FLUX_IMUL=FLUX_MUL,
    FLUX_IDIV=FLUX_DIV,
    FLUX_IMOD=FLUX_MOD,
    FLUX_IREM=FLUX_MOD,
    FLUX_IAND=FLUX_AND,
    FLUX_IOR=FLUX_OR,
    FLUX_IXOR=FLUX_XOR,
    FLUX_ISHL=FLUX_SHL,
    FLUX_ISHR=FLUX_SHR,
    FLUX_ROTL=FLUX_SHL,
    FLUX_ROTR=FLUX_SHR,
    FLUX_INEG=FLUX_NEG,
    FLUX_CMP=FLUX_CMP_EQ,
    FLUX_ICMP=FLUX_CMP_EQ,
    FLUX_IEQ=FLUX_CMP_EQ,
    FLUX_ILT=FLUX_CMP_LT,
    FLUX_IGT=FLUX_CMP_GT,
    FLUX_ILE=FLUX_CMP_LT,
    FLUX_IGE=FLUX_CMP_GT,
} FluxOpcode;

const char* flux_opcode_name(uint8_t op);
#define FLUX_OPCODE_COUNT 133

#ifdef __cplusplus
}
#endif
#endif
